# .bash_profile

# Get the aliases and functions
if [[ -z $PS1 && -f ~/.bashrc ]]; then # If PS1 is not defined, then we'll source ~/.bashrc
	. ~/.bashrc
fi

# User specific environment and startup programs

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
export PATH="/home/linuxbrew/.linuxbrew/opt/node@12/bin:$PATH"

export PATH=$PATH:$HOME/.local/bin:$HOME/bin

export GIT_UTILITIES_BIN="~/GitHub/rkiel/git-utilities/bin"
export NODE_UTILITIES_BIN="~/GitHub/rkiel/node-utilities/bin"
export PATH=${GIT_UTILITIES_BIN}:$PATH
export PATH=${NODE_UTILITIES_BIN}:$PATH

export DOT_USER=despinoza
export FEATURE_USER=despinoza

export SAM_CLI_TELEMETRY=0
