# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

source ~/GitHub/rkiel/git-utilities/dotfiles/bashrc
source ~/GitHub/rkiel/git-utilities/dotfiles/git-completion.bash
source ~/GitHub/rkiel/git-utilities/dotfiles/git-prompt.sh

export PS1='[\[\e[0;35m\]\u@\h\[\e[0m\] \[\e[1;34m\]\W\[\e[0;32m\]$(__git_ps1 " %s")\[\e[0m\]]\$ '

alias ll="ls -la --color=auto"
alias npml="npm list --depth=0"

alias app="npm run app:start"
alias clean="git checkout master; git pull; git remote update; git remote prune origin; git gc; git branch -a"
alias karma="npm run karma:start"
alias status="git status; echo; echo STASH:; git stash list; echo"
alias watch="npm run app:watch"

alias killnode="taskkill -F -IM node.exe"

alias api="cd ~/projects/expense-app-api"
alias dot="cd ~/projects/dotFiles"
alias ea="cd ~/projects/vue-expense-app"

# ----------
# Git Aliases
# ----------
alias ga='git add'
alias gb='git branch'
alias gbd='git branch -d '
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gd='git diff'
alias gl='git log'
alias glg='git log --graph --oneline --decorate --all'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gm='git merge --no-ff'
alias gp='git pull'
alias gs='git status'
alias gss='git status -s'
alias gst='git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'
