# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

source ~/GitHub/rkiel/git-utilities/dotfiles/bashrc
source ~/GitHub/rkiel/git-utilities/dotfiles/git-completion.bash
source ~/GitHub/rkiel/git-utilities/dotfiles/git-prompt.sh
source ~/GitHub/rkiel/node-utilities/dotfiles/bashrc

export PS1='[\[\e[0;35m\]\u@\h\[\e[0m\] \[\e[1;34m\]\W\[\e[0;32m\]$(__git_ps1 " %s")\[\e[0m\]]\$ '

alias ll="ls -la --color=auto"
alias npml="npm list --depth=0"

alias app="npm run app:start"
alias clean="git checkout main; git checkout master; git pull; git remote update; git remote prune origin; git gc; git branch -a"
alias karma="npm run karma:start"
alias status="git status; echo; echo STASH:; git stash list; echo"
alias watch="npm run app:watch"

alias killnode="taskkill -F -IM node.exe"
alias sam="'/c/Program Files/Amazon/AWSSAMCLI/bin/sam.cmd'"

alias adp="cd ~/projects/auth-delphi-pythia"
alias api="cd ~/projects/expense-app-api"
alias aw="cd ~/projects/app-website"
alias da="cd ~/projects/delphi-api"
alias delphi="cd ~/projects/app-delphi"
alias dp="cd ~/projects/delphi-pythia"
alias dot="cd ~/projects/dotFiles"
alias ea="cd ~/projects/vue-expense-app"
alias eapi="cd ~/projects/expense-app-api"
alias gifbot="cd ~/projects/lambda-gifbot"
alias insultbot="cd ~/projects/lambda-insultbot"
alias memebot="cd ~/projects/lambda-memebot"
alias pa="cd ~/projects/pythia-api"
alias pythia="cd ~/projects/app-pythia"
alias mysterio="cd ~/projects/mysterio"
alias website="cd ~/projects/app-website"
alias wapi="cd ~/projects/website-api"
