# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:/usr/lib/oracle/12.2/client64/bin
PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin
PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=$PATH:"/c/Program Files/nodejs":"/c/Users/mfran/AppData/Local/atom/bin"
PATH=$PATH:"/c/Ruby24-x64/bin"
PATH=$PATH:"/c/Program Files/Amazon/AWSSAMCLI/bin"

export SAM_CLI_TELEMETRY=0

export GIT_UTILITIES_BIN="~/GitHub/rkiel/git-utilities/bin"
export NODE_UTILITIES_BIN="~/GitHub/rkiel/node-utilities/bin"

export PATH=${GIT_UTILITIES_BIN}:$PATH
export PATH=${NODE_UTILITIES_BIN}:$PATH

export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib

export DOT_USER=mfrank
export FEATURE_USER=mfrank
