# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

GIT_UTILITIES=~/GitHub/rkiel/git-utilities
source ${GIT_UTILITIES}/dotfiles/bashrc

NODE_UTILITIES=~/GitHub/rkiel/node-utilities
source ${NODE_UTILITIES}/dotfiles/bashrc
